# COMP 352 – Final Project: Footballer Market Evaluation  
**Goal:** To predict the market value of a prefessional footballer next year  

**Authors:** Zevin Attisha, Christian Vaikona, Santiago Guerrero, Santiago Pedetti   

**Dataset source:** https://www.kaggle.com/datasets/davidcariboo/player-scores  

---

## Table of Contents
1. Environment Setup  
2. Data Importing and Pre-processing  
3. Data Analysis and Visualization  
4. Data Analytics (Modeling)  
5. Summary / Conclusions

## 1. Data Importing and Pre-processing
- Import dataset and describe characteristics such as dimensions, data types, file types, and import methods used
- Clean, wrangle, and handle missing data, duplicate data, etc.
- Encode any categorical variables
- Perform feature engineering on the dataset
- Transform data appropriately using techniques such as aggregation, normalization, and feature construction
- Reduce redundant data and perform need based discretization

We utilize four datasets:
- `player_valuations.csv`: multiple valuation records per player over time
- `players.csv`: one record per player with demographic and categorical info
- `appearances.csv`: one record per player with statistics per game appareance
- `game_lineups.csv`: one record per player with status per game

### Environment Setup

[WILL ADD REPRODUCABLE STEPS ONCE COMPLETE]

In [414]:
# Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, TimeSeriesSplit, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression, ElasticNet
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

# Functions from other scripts
from helper_scripts import (
    evaluate_model,
    cv_mae,
    remove_duplicates # Currently not working as desired
)

# Dataframe formatting
pd.set_option("display.max_columns", None)
np.set_printoptions(suppress=True)

In [415]:
# Creating variables for csv paths
PATH_PLAYER_VALUATIONS = "data/raw/player_valuations.csv"
PATH_PLAYERS = "data/raw/players.csv"
PATH_APPEARANCES = "data/raw/appearances.csv"
PATH_LINEUPS = "data/raw/game_lineups.csv"  

# Creating Pandas dataframes
player_valuations_df = pd.read_csv(PATH_PLAYER_VALUATIONS)
players_df = pd.read_csv(PATH_PLAYERS)
appearances_df = pd.read_csv(PATH_APPEARANCES)
lineups_df = pd.read_csv(PATH_LINEUPS)    

# Displaying dataframe shapes
print("-"*60)
print("Dataframe Shapes")
print("-"*60)

print("player_valuations_df shape:", player_valuations_df.shape)
print("players_df shape:", players_df.shape)
print("appearances_df shape:", appearances_df.shape)
print("lineups_df shape:", lineups_df.shape) 
print("\n")

# Displaying dataframe heads
print("-"*60)
print("Dataframe Heads")
print("-"*60)

print("player_valuations_df:")
display(player_valuations_df.head())

print("\nplayers_df:")
display(players_df.head())

print("\nappearances_df:")
display(appearances_df.head())

print("\nlineups_df:")
display(lineups_df.head())

------------------------------------------------------------
Dataframe Shapes
------------------------------------------------------------
player_valuations_df shape: (496606, 5)
players_df shape: (32601, 23)
appearances_df shape: (1706806, 13)
lineups_df shape: (2191911, 10)


------------------------------------------------------------
Dataframe Heads
------------------------------------------------------------
player_valuations_df:

,player_id,date,market_value_in_eur,current_club_id,player_club_domestic_competition_id
0,405973,2000-01-20,150000,3057,BE1
1,342216,2001-07-20,100000,1241,SC1
2,3132,2003-12-09,400000,126,TR1
3,6893,2003-12-15,900000,984,GB1
4,10,2004-10-04,7000000,398,IT1

players_df:

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,date_of_birth,sub_position,position,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,1978-06-09 00:00:00,Centre-Forward,Attack,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,1980-08-06 00:00:00,Goalkeeper,Goalkeeper,left,190.0,NaN,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,1981-01-30 00:00:00,Centre-Forward,Attack,NaN,NaN,NaN,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,1978-05-08 00:00:00,Centre-Back,Defender,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,1981-03-18 00:00:00,Goalkeeper,Goalkeeper,right,194.0,NaN,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.0,3000000.0

appearances_df:

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,Aurélien Joachim,CLQ,0,0,2,0,90
1,2233748_79232,2233748,79232,8841,2698,2012-07-05,Ruslan Abyshov,ELQ,0,0,0,0,90
2,2234413_42792,2234413,42792,6251,465,2012-07-05,Sander Puri,ELQ,0,0,0,0,45
3,2234418_73333,2234418,73333,1274,6646,2012-07-05,Vegar Hedenstad,ELQ,0,0,0,0,90
4,2234421_122011,2234421,122011,195,3008,2012-07-05,Markus Henriksen,ELQ,0,0,0,1,90

lineups_df:

,game_lineups_id,date,game_id,player_id,club_id,player_name,type,position,number,team_captain
0,b2dbe01c3656b06c8e23e9de714e26bb,2013-07-27,2317258,1443,610,Christian Poulsen,substitutes,Defensive Midfield,5,0
1,b50a3ec6d52fd1490aab42042ac4f738,2013-07-27,2317258,5017,610,Niklas Moisander,starting_lineup,Centre-Back,4,0
2,7d890e6d0ff8af84b065839966a0ec81,2013-07-27,2317258,9602,1090,Maarten Martens,substitutes,Left Winger,11,0
3,8c355268678b9bbc7084221b1f0fde36,2013-07-27,2317258,12282,610,Daley Blind,starting_lineup,Left-Back,17,0
4,76193074d549e5fdce4cdcbba0d66247,2013-07-27,2317258,25427,1090,Roy Beerens,starting_lineup,Right Winger,23,0

In [416]:
# Checking for duplicates
# (Helper function for repeated code won't format results correctly - helper_scripts.py)

# player_valuations_df
print("-"*30)
print("Player Valuations Dataset")
print("-"*30)
print(f"Total rows: {len(player_valuations_df)}")
print(f"Duplicate rows: {player_valuations_df.duplicated().sum()}")
if player_valuations_df.duplicated().sum() > 0:
    print(f"Removing {player_valuations_df.duplicated().sum()} duplicate rows...")
    player_valuations_df = player_valuations_df.drop_duplicates()
    print(f"Rows after removing duplicates: {len(player_valuations_df)}")
else:
    print("No duplicate rows found.")

# players_df
print("-"*30)
print("Players Dataset")
print("-"*30)
print(f"Total rows: {len(players_df)}")
print(f"Duplicate rows: {players_df.duplicated().sum()}")
if players_df.duplicated().sum() > 0:
    print(f"Removing {players_df.duplicated().sum()} duplicate rows...")
    players_df = players_df.drop_duplicates()
    print(f"Rows after removing duplicates: {len(players_df)}")
else:
    print("No duplicate rows found.")

# appearances_df
print("-"*30)
print("Appearances Dataset")
print("-"*30)
print(f"Total rows: {len(appearances_df)}")
print(f"Duplicate rows: {appearances_df.duplicated().sum()}")
if appearances_df.duplicated().sum() > 0:
    print(f"Removing {appearances_df.duplicated().sum()} duplicate rows...")
    appearances_df = appearances_df.drop_duplicates()
    print(f"Rows after removing duplicates: {len(appearances_df)}")
else:
    print("No duplicate rows found.")

# lineups_df
print("-"*30)
print("Lineups Dataset")
print("-"*30)
print(f"Total rows: {len(lineups_df)}")
print(f"Duplicate rows: {lineups_df.duplicated().sum()}")
if lineups_df.duplicated().sum() > 0:
    print(f"Removing {lineups_df.duplicated().sum()} duplicate rows...")
    lineups_df = lineups_df.drop_duplicates()
    print(f"Rows after removing duplicates: {len(lineups_df)}")
else:
    print("No duplicate rows found.")

# TESTING HELPER FUNCTION
# lineups_df
# print("\n Lineups Dataset")
# remove_duplicates(lineups_df) # Won't format like above code

------------------------------
Player Valuations Dataset
------------------------------
Total rows: 496606
Duplicate rows: 0
No duplicate rows found.
------------------------------
Players Dataset
------------------------------
Total rows: 32601
Duplicate rows: 0
No duplicate rows found.
------------------------------
Appearances Dataset
------------------------------
Total rows: 1706806
Duplicate rows: 0
No duplicate rows found.
------------------------------
Lineups Dataset
------------------------------
Total rows: 2191911
Duplicate rows: 0
No duplicate rows found.

In [417]:
# Types per dataset
print("player_valuations_df dtypes:")
display(player_valuations_df.dtypes)

print("\nplayers_df dtypes:")
display(players_df.dtypes)

print("\nappearances_df dtypes:")
display(appearances_df.dtypes)

print("\nlineups_df dtypes:")
display(lineups_df.dtypes)
print("\n")

# Columns that display the most missing values in descending order
print("-"*60)
print("Missing Values in player_valuations_df:")
print("-"*60)
display(player_valuations_df.isna().sum().sort_values(ascending=False).head(len(player_valuations_df)))

print("-"*60)
print("Missing values in players_df:")
print("-"*60)
display(players_df.isna().sum().sort_values(ascending=False).head(len(players_df)))

print("-"*60)
print("Missing values in appearances_df:")
print("-"*60)
display(appearances_df.isna().sum().sort_values(ascending=False).head(len(appearances_df)))

print("-"*60)
print("Missing values in lineups_df:")
print("-"*60)
display(lineups_df.isna().sum().sort_values(ascending=False).head(len(lineups_df)))

player_valuations_df dtypes:

player_id                               int64
date                                   object
market_value_in_eur                     int64
current_club_id                         int64
player_club_domestic_competition_id    object
dtype: object

players_df dtypes:

player_id                                 int64
first_name                               object
last_name                                object
name                                     object
last_season                               int64
current_club_id                           int64
player_code                              object
country_of_birth                         object
city_of_birth                            object
country_of_citizenship                   object
date_of_birth                            object
sub_position                             object
position                                 object
foot                                     object
height_in_cm                            float64
contract_expiration_date                 object
agent_name                               object
image_url                                object
url                                      object
current_club_domestic_competition_id     object
current_club_name                        object
market_value_in_eur                     float64
highest_market_value_in_eur             float64
dtype: object

appearances_df dtypes:

appearance_id             object
game_id                    int64
player_id                  int64
player_club_id             int64
player_current_club_id     int64
date                      object
player_name               object
competition_id            object
yellow_cards               int64
red_cards                  int64
goals                      int64
assists                    int64
minutes_played             int64
dtype: object

lineups_df dtypes:

game_lineups_id    object
date               object
game_id             int64
player_id           int64
club_id             int64
player_name        object
type               object
position           object
number             object
team_captain        int64
dtype: object

------------------------------------------------------------
Missing Values in player_valuations_df:
------------------------------------------------------------

player_id                              0
date                                   0
market_value_in_eur                    0
current_club_id                        0
player_club_domestic_competition_id    0
dtype: int64

------------------------------------------------------------
Missing values in players_df:
------------------------------------------------------------

agent_name                              16019
contract_expiration_date                12091
country_of_birth                         2799
foot                                     2536
city_of_birth                            2455
height_in_cm                             2256
first_name                               2062
highest_market_value_in_eur              1523
market_value_in_eur                      1523
country_of_citizenship                    383
sub_position                              180
date_of_birth                              47
position                                    0
player_code                                 0
current_club_id                             0
last_season                                 0
name                                        0
image_url                                   0
url                                         0
current_club_domestic_competition_id        0
current_club_name                           0
last_name                                   0
player_id                                   0
dtype: int64

------------------------------------------------------------
Missing values in appearances_df:
------------------------------------------------------------

player_name               6
appearance_id             0
game_id                   0
player_id                 0
player_club_id            0
player_current_club_id    0
date                      0
competition_id            0
yellow_cards              0
red_cards                 0
goals                     0
assists                   0
minutes_played            0
dtype: int64

------------------------------------------------------------
Missing values in lineups_df:
------------------------------------------------------------

position           3
game_lineups_id    0
date               0
game_id            0
player_id          0
club_id            0
player_name        0
type               0
number             0
team_captain       0
dtype: int64

In [418]:
# Clean players_df

# Copy to avoid altering original data
p = players_df.copy()

# Sort by player
p = p.sort_values(['player_id']).reset_index(drop=True)

# Drop where target variable isn't available
p = p.dropna(subset=["highest_market_value_in_eur"]) # Also ends up clearing nulls in "market_value_in_eur"

# Parse birth date
p["date_of_birth"] = pd.to_datetime(p["date_of_birth"], errors="coerce")

# Birth date required for age feature
p = p.dropna(subset=["date_of_birth"])

# Having both position and sub_position provides cleaner statistical analysis
p = p.dropna(subset=["sub_position"]) # Removes "Missing" values from position also

# Drop to make right vs left foot correlation feature or impute for general use?
p = p.dropna(subset=["foot"])
# OR
# p["foot"] = p["foot"].fillna("Missing")

# Save original names before encoding
p['sub_position_name'] = p['sub_position'].copy()
p['position_name'] = p['position'].copy()
p['foot_name'] = p['foot'].copy()

# Label encoding for foot
foot_map = {'left': 0, 'right': 1, 'both': 2}
p['foot_encoded'] = p['foot'].map(foot_map)

# One-hot encoding for position
p = pd.get_dummies(p, columns=['position'], prefix='pos', drop_first=False, dtype=int)
position_cols = [col for col in p.columns if col.startswith('pos_')]

# Frequency encoding for sub_position
subpos_freq = p['sub_position'].value_counts(normalize=True)
p['sub_position'] = p['sub_position'].map(subpos_freq)
p = p.rename(columns={'sub_position': 'sub_position_freq'})

# Handle missing categoricals 
# p["sub_position"] = p["sub_position"].fillna("Missing")

# # Numeric height + impute (less than 3% of height values were null)
p["height_in_cm"] = pd.to_numeric(p["height_in_cm"], errors="coerce")
p["height_in_cm"] = p["height_in_cm"].fillna(p["height_in_cm"].median()) 

# Keep only safe player-level features (no bias/leakage)
"""
Dropping The Following:

[Cannot Impute]
agent_name
contract_expiration_date
first_name
country_of_birth
city_of_birth
country_of_citizenship

[Irrelavant/Bias]
market_value_in_eur
current_club_domestic_competition_id
url
image_url
player_code
last_season
name
last_name
highest_market_value_in_eur

[Encoded]
foot - label encoding - simpler 0/1/2 to left/right/both
position - one-hot encoding - only 4 series added
sub_position - frequency encoding - At risk of data leakage if 13 different series created or values encoded

[Potentially Bring Back For Feature]
current_club_name OR current_club_id - frequency of players at a club correlation to value
"""
keep_player_cols = [
    "player_id",
    "height_in_cm",
    "sub_position_name",
    "sub_position_freq",
    "foot_name",
    "foot_encoded",
    "date_of_birth",
    "position_name"
] + position_cols
p = p[keep_player_cols].copy()

print("p shape:", p.shape)
p.head()

# Keep here at bottom to check on df when needed
# print("-"*60)
# print("Missing values in players_df:")
# print("-"*60)
# display(p.isna().sum().sort_values(ascending=False).head(len(p)))

p shape: (29054, 12)

,player_id,height_in_cm,sub_position_name,sub_position_freq,foot_name,foot_encoded,date_of_birth,position_name,pos_Attack,pos_Defender,pos_Goalkeeper,pos_Midfield
0,10,184.0,Centre-Forward,0.140497,right,1,1978-06-09,Attack,1,0,0,0
1,26,190.0,Goalkeeper,0.104977,left,0,1980-08-06,Goalkeeper,0,0,1,0
4,80,194.0,Goalkeeper,0.104977,right,1,1981-03-18,Goalkeeper,0,0,1,0
7,132,179.0,Attacking Midfield,0.068803,both,2,1980-10-04,Midfield,0,0,0,1
8,162,193.0,Goalkeeper,0.104977,right,1,1976-06-13,Goalkeeper,0,0,1,0

In [419]:
# Clean appearances_df

# Copy to avoid altering original data
app = appearances_df.copy()

# Parse date to datetime
app['date'] = pd.to_datetime(app['date'], errors='coerce')

# Extract year from match date
app['year'] = app['date'].dt.year 

# Fill missing performance stats with 0 (player appeared but didn't score/assist)
app['yellow_cards'] = app['yellow_cards'].fillna(0)
app['red_cards'] = app['red_cards'].fillna(0)
app['goals'] = app['goals'].fillna(0)
app['assists'] = app['assists'].fillna(0)
app['minutes_played'] = app['minutes_played'].fillna(0)

# Keep only safe player-level features (no bias/leakage)
"""
Dropping The Following:

player_name - player_id is present
appearance_id
game_id
player_club_id
player_current_club_id
competition_id
"""
keep_player_cols = [
    "player_id",
    "date",
    "yellow_cards",
    "red_cards",
    "goals",
    "assists",
    "minutes_played",
    "year" 
]
app = app[keep_player_cols].copy()

print("app shape:", app.shape)
app.head()

# Keep here at bottom to check on df when needed
# print("-"*60)
# print("Missing values in appearances_df:")
# print("-"*60)
# display(app.isna().sum().sort_values(ascending=False).head(len(app)))

app shape: (1706806, 8)

,player_id,date,yellow_cards,red_cards,goals,assists,minutes_played,year
0,38004,2012-07-03,0,0,2,0,90,2012
1,79232,2012-07-05,0,0,0,0,90,2012
2,42792,2012-07-05,0,0,0,0,45,2012
3,73333,2012-07-05,0,0,0,0,90,2012
4,122011,2012-07-05,0,0,0,1,90,2012

In [420]:
# Clean player_valuations_df

# Copy to avoid altering original data
pv = player_valuations_df.copy()

# Parse date
pv["date"] = pd.to_datetime(pv["date"], errors="coerce")

# Sort by player and date
pv = pv.sort_values(['player_id', 'date']).reset_index(drop=True)

"""
Dropping the following:

current_club_id
player_club_domestic_competition_id
"""
keep_player_cols = [
    "player_id",
    "date",
    "market_value_in_eur"
]
pv = pv[keep_player_cols].copy()

print(f"pv shape: {pv.shape}")
print(f"Date range: {pv['date'].min()} to {pv['date'].max()}")
print(f"Unique players: {pv['player_id'].nunique()}")
print("pv head:")
pv.head()

# Keep here at bottom to check on df when needed
# print("-"*60)
# print("Missing values in player_valuations_df:")
# print("-"*60)
# display(pv.isna().sum().sort_values(ascending=False).head(len(pv)))

pv shape: (496606, 3)
Date range: 2000-01-20 00:00:00 to 2025-04-06 00:00:00
Unique players: 31078
pv head:

   player_id       date  market_value_in_eur
0         10 2004-10-04              7000000
1         10 2005-01-07              9000000
2         10 2005-05-05             12000000
3         10 2005-09-30             15000000
4         10 2006-01-09             20000000

In [421]:
# Clean lineups_df

# Copy to avoid altering original data
lu = lineups_df.copy()

# Parse date
lu["date"] = pd.to_datetime(lu["date"], errors="coerce")

# Sort by player and date
lu = lu.sort_values(['player_id', 'date']).reset_index(drop=True)

# Dropping where position is not available
# lu = lu.dropna(subset=["position"])

# Renaming type column and label encoding values
# Simplified to indicate if starter or not per appearance
lu = lu.rename(columns={"type": "is_starter"})
type_map = {'substitutes': 0, 'starting_lineup': 1}
lu['is_starter'] = lu['is_starter'].map(type_map)

# Dropping where positon is outdated or categorical, not specific
# lu = lu[~lu['position'].isin(['midfield', 'Attack', 'Defender', 'Sweeper'])]

""" 
Dropping the following:

game_lineups_id
game_id
club_id
player_name
number
position - present in p (cleaned players_df)
"""
keep_player_cols = [
    "date",
    "player_id",
    "is_starter",
    "team_captain"
]
lu = lu[keep_player_cols].copy()
print("lu shape:", lu.shape)
lu.head()

# Keep here at bottom to check on df when needed
# print("-"*60)
# print("Missing values in lineups_df:")
# print("-"*60)
# display(lu.isna().sum().sort_values(ascending=False).head(len(lu)))

lu shape: (2191911, 4)

        date  player_id  is_starter  team_captain
0 2013-08-18         10           1             0
1 2013-08-25         10           1             0
2 2013-08-31         10           1             0
3 2013-09-15         10           1             0
4 2013-09-19         10           0             0

In [422]:
# Lifetime Cumulative Statistics - app

# Sort by player and date
app = app.sort_values(['player_id', 'date']).reset_index(drop=True)

# Creating cumulative features
app['total_goals'] = app.groupby(['player_id'])['goals'].cumsum()
app['total_assists'] = app.groupby(['player_id'])['assists'].cumsum()
app['total_minutes'] = app.groupby(['player_id'])['minutes_played'].cumsum()
app['total_yellow_cards'] = app.groupby(['player_id'])['yellow_cards'].cumsum()
app['total_red_cards'] = app.groupby(['player_id'])['red_cards'].cumsum()
app['total_appearances'] = app.groupby(['player_id']).cumcount() + 1 # +1 because of 0-based count

'''grit feature- FEATURE FOR GOAL to yellow or red card CORRELATION 

  '''

# Goal, assist, yellow-card, red-card rate
app['goal_rate'] = round(app['total_goals'] / app['total_appearances'],3)
app['assist_rate'] = round(app['total_assists'] / app['total_appearances'],3)
app['yellow_card_rate'] = round(app['total_yellow_cards'] / app['total_appearances'],3)
app['red_card_rate'] = round(app['total_red_cards'] / app['total_appearances'],3)

# Keep only the most recent row per player per date (in case multiple games same day)
app_cumulative = app.groupby(['player_id', 'date']).tail(1).reset_index(drop=True)

# Select columns for merge
app_for_merge = app_cumulative[[
    'player_id', 'date',
    'total_goals', 'total_assists', 'total_minutes',
    'total_yellow_cards', 'total_red_cards', 'total_appearances',
    'goal_rate', 'assist_rate', 'yellow_card_rate', 'red_card_rate'
]].copy()

# Verify cumulative logic is working correctly
print("\nChecking cumulative growth for a sample player:")
sample_player_id = app_for_merge['player_id'].iloc[100] if len(app_for_merge) > 100 else app_for_merge['player_id'].iloc[0]
sample_data = app_for_merge[app_for_merge['player_id'] == sample_player_id].head(10)
print(f"\nPlayer ID: {sample_player_id}")
display(sample_data[['date', 'total_goals', 'total_assists', 'total_minutes','total_yellow_cards', 'total_red_cards', 'total_appearances', 
                     'goal_rate', 'assist_rate', 'yellow_card_rate', 'red_card_rate']])
print("All numerical stats should either remain constant or increase as time goes on")

print(f"\napp_for_merge shape: {app_for_merge.shape}")
print(f"Date range: {app_for_merge['date'].min()} to {app_for_merge['date'].max()}")
print(f"Unique players: {app_for_merge['player_id'].nunique()}")
print("\napp_for_merge head:")
app_for_merge.head()

# Keep here at bottom to check on df when needed
# print("-"*60)
# print("Missing values in app_for_merge:")
# print("-"*60)
# display(app_for_merge.isna().sum().sort_values(ascending=False).head(len(app_for_merge)))

Checking cumulative growth for a sample player:

Player ID: 10

,date,total_goals,total_assists,total_minutes,total_yellow_cards,total_red_cards,total_appearances,goal_rate,assist_rate,yellow_card_rate,red_card_rate
0,2012-08-23,1,0,83,1,0,1,1.000,0.000,1.000,0.0
1,2012-08-26,1,0,173,2,0,2,0.500,0.000,1.000,0.0
2,2012-09-02,3,0,262,3,0,3,1.000,0.000,1.000,0.0
3,2012-09-16,4,0,352,3,0,4,1.000,0.000,0.750,0.0
4,2012-09-20,4,0,442,3,0,5,0.800,0.000,0.600,0.0
5,2012-09-23,4,0,456,3,0,6,0.667,0.000,0.500,0.0
6,2012-09-26,4,0,546,3,0,7,0.571,0.000,0.429,0.0
7,2012-09-30,4,1,636,4,0,8,0.500,0.125,0.500,0.0
8,2012-10-07,6,1,708,4,0,9,0.667,0.111,0.444,0.0
9,2012-10-20,7,1,798,4,0,10,0.700,0.100,0.400,0.0

All numerical stats should either remain constant or increase as time goes on

app_for_merge shape: (1706792, 12)
Date range: 2012-07-03 00:00:00 to 2025-04-10 00:00:00
Unique players: 25689

app_for_merge head:

,player_id,date,total_goals,total_assists,total_minutes,total_yellow_cards,total_red_cards,total_appearances,goal_rate,assist_rate,yellow_card_rate,red_card_rate
0,10,2012-08-23,1,0,83,1,0,1,1.0,0.0,1.00,0.0
1,10,2012-08-26,1,0,173,2,0,2,0.5,0.0,1.00,0.0
2,10,2012-09-02,3,0,262,3,0,3,1.0,0.0,1.00,0.0
3,10,2012-09-16,4,0,352,3,0,4,1.0,0.0,0.75,0.0
4,10,2012-09-20,4,0,442,3,0,5,0.8,0.0,0.60,0.0

In [423]:
# Lifetime Cumulative Statistics - lu

# Sort by player and date
lu = lu.sort_values(['player_id', 'date']).reset_index(drop=True)

# Creating cumulative features
lu['total_starts'] = lu.groupby(['player_id'])['is_starter'].cumsum()
lu['total_captaincies'] = lu.groupby(['player_id'])['team_captain'].cumsum()

# Create a total games count within the lu dataframe itself
lu['total_games_in_lineup'] = lu.groupby(['player_id']).cumcount() + 1

# Live rates for tendency to start or be captain throughout career
lu['captain_rate'] = round(lu['total_captaincies'] / lu['total_games_in_lineup'], 3)
lu['starting_rate'] = round(lu['total_starts'] / lu['total_games_in_lineup'], 3)

# Keep only the most recent row per player per date (in case multiple games same day)
lu_cumulative = lu.groupby(['player_id', 'date']).tail(1).reset_index(drop=True)

# Select columns for merge
lu_for_merge = lu_cumulative[[
    'player_id', 
    'date',
    'is_starter',
    'total_starts',
    'team_captain',
    'total_captaincies',
    'starting_rate',
    'captain_rate'
]].copy()

# Verify cumulative logic is working correctly
print("\nChecking cumulative growth for a sample player:")
sample_player_id = lu_for_merge['player_id'].iloc[100] if len(lu_for_merge) > 100 else lu_for_merge['player_id'].iloc[0]
sample_data = lu_for_merge[lu_for_merge['player_id'] == sample_player_id].head(10)
print(f"\nPlayer ID: {sample_player_id}")
display(sample_data[['date', 'total_starts', 'total_captaincies', 'starting_rate', 'captain_rate' ]])
print("All stats should either remain constant or increase as time goes on")

print(f"\nlu_for_merge shape: {lu_for_merge.shape}")
print(f"Date range: {lu_for_merge['date'].min()} to {lu_for_merge['date'].max()}")
print(f"Unique players: {lu_for_merge['player_id'].nunique()}")
print("\nlu_for_merge head:")
lu_for_merge.head()

# Keep here at bottom to check on df when needed
# print("-"*60)
# print("Missing values in lu_for_merge:")
# print("-"*60)
# display(lu_for_merge.isna().sum().sort_values(ascending=False).head(len(lu_for_merge)))

Checking cumulative growth for a sample player:

Player ID: 10

        date  total_starts  total_captaincies  starting_rate  captain_rate
0 2013-08-18             1                  0          1.000           0.0
1 2013-08-25             2                  0          1.000           0.0
2 2013-08-31             3                  0          1.000           0.0
3 2013-09-15             4                  0          1.000           0.0
4 2013-09-19             4                  0          0.800           0.0
5 2013-09-22             5                  0          0.833           0.0
6 2013-10-20             5                  0          0.714           0.0
7 2013-10-27             5                  0          0.625           0.0
8 2013-10-30             6                  0          0.667           0.0
9 2013-11-03             7                  0          0.700           0.0

All stats should either remain constant or increase as time goes on

lu_for_merge shape: (2191895, 8)
Date range: 2013-07-02 00:00:00 to 2024-03-17 00:00:00
Unique players: 85235

lu_for_merge head:

,player_id,date,is_starter,total_starts,team_captain,total_captaincies,starting_rate,captain_rate
0,10,2013-08-18,1,1,0,0,1.0,0.0
1,10,2013-08-25,1,2,0,0,1.0,0.0
2,10,2013-08-31,1,3,0,0,1.0,0.0
3,10,2013-09-15,1,4,0,0,1.0,0.0
4,10,2013-09-19,0,4,0,0,0.8,0.0

### CHECKPOINT 1
4 Tables have been curated:
- `p` : player_id, height_in_cm, sub_position, foot_encoded, date_of_birth, pos_Attack, pos_Defender, pos_Goalkeeper, pos_Midfield
- `pv` : player_id, date, market_value_in_eur
- `app_for_merge` : player_id, date, total_goals, total_assists, total_minutes, total_yellow_cards, total_red_cards, total_appearances, goal_rate, assist_rate, yellow_card_rate, red_card_rate
- `lu_for_merge` : player_id, date, is_starter, total_starts, team_captain, total_captaincies, starting_rate, captain_rate

In [424]:
print(f"p shape: {p.shape}")
print(f"Unique players: {p['player_id'].nunique()}")
print("p head:")
display(p.head())

print(f"pv shape: {pv.shape}")
print(f"Date range: {pv['date'].min()} to {pv['date'].max()}")
print(f"Unique players: {pv['player_id'].nunique()}")
print("pv head:")
display(pv.head())

print(f"app_for_merge shape: {app_for_merge.shape}")
print(f"Date range: {app_for_merge['date'].min()} to {app_for_merge['date'].max()}")
print(f"Unique players: {app_for_merge['player_id'].nunique()}")
print("app_for_merge head:")
display(app_for_merge.head())

print(f"lu_for_merge shape: {lu_for_merge.shape}")
print(f"Date range: {lu_for_merge['date'].min()} to {lu_for_merge['date'].max()}")
print(f"Unique players: {lu_for_merge['player_id'].nunique()}")
print("lu_for_merge head:")
display(lu_for_merge.head())

p shape: (29054, 12)
Unique players: 29054
p head:

,player_id,height_in_cm,sub_position_name,sub_position_freq,foot_name,foot_encoded,date_of_birth,position_name,pos_Attack,pos_Defender,pos_Goalkeeper,pos_Midfield
0,10,184.0,Centre-Forward,0.140497,right,1,1978-06-09,Attack,1,0,0,0
1,26,190.0,Goalkeeper,0.104977,left,0,1980-08-06,Goalkeeper,0,0,1,0
4,80,194.0,Goalkeeper,0.104977,right,1,1981-03-18,Goalkeeper,0,0,1,0
7,132,179.0,Attacking Midfield,0.068803,both,2,1980-10-04,Midfield,0,0,0,1
8,162,193.0,Goalkeeper,0.104977,right,1,1976-06-13,Goalkeeper,0,0,1,0

pv shape: (496606, 3)
Date range: 2000-01-20 00:00:00 to 2025-04-06 00:00:00
Unique players: 31078
pv head:

   player_id       date  market_value_in_eur
0         10 2004-10-04              7000000
1         10 2005-01-07              9000000
2         10 2005-05-05             12000000
3         10 2005-09-30             15000000
4         10 2006-01-09             20000000

app_for_merge shape: (1706792, 12)
Date range: 2012-07-03 00:00:00 to 2025-04-10 00:00:00
Unique players: 25689
app_for_merge head:

,player_id,date,total_goals,total_assists,total_minutes,total_yellow_cards,total_red_cards,total_appearances,goal_rate,assist_rate,yellow_card_rate,red_card_rate
0,10,2012-08-23,1,0,83,1,0,1,1.0,0.0,1.00,0.0
1,10,2012-08-26,1,0,173,2,0,2,0.5,0.0,1.00,0.0
2,10,2012-09-02,3,0,262,3,0,3,1.0,0.0,1.00,0.0
3,10,2012-09-16,4,0,352,3,0,4,1.0,0.0,0.75,0.0
4,10,2012-09-20,4,0,442,3,0,5,0.8,0.0,0.60,0.0

lu_for_merge shape: (2191895, 8)
Date range: 2013-07-02 00:00:00 to 2024-03-17 00:00:00
Unique players: 85235
lu_for_merge head:

,player_id,date,is_starter,total_starts,team_captain,total_captaincies,starting_rate,captain_rate
0,10,2013-08-18,1,1,0,0,1.0,0.0
1,10,2013-08-25,1,2,0,0,1.0,0.0
2,10,2013-08-31,1,3,0,0,1.0,0.0
3,10,2013-09-15,1,4,0,0,1.0,0.0
4,10,2013-09-19,0,4,0,0,0.8,0.0

In [425]:
# Merging pv and p

# Merge pv (Player Valuations) with p (Player Info)
valuation_profiles = pv.merge(p, on='player_id', how='left')

# Choosing series to drop all rows with null values at all
# Rows only have nulls if there was no player information to join to the valuations
# Dropped records should account for all records of any player_id that was dropped in the process
valuation_profiles = valuation_profiles.dropna(subset=["foot_name"])

# Create age at valuation
valuation_profiles['age_at_valuation'] = round((valuation_profiles['date'] - valuation_profiles['date_of_birth']).dt.days / 365.25,2)

# Ensuring general types
valuation_profiles = valuation_profiles.astype({'player_id': int,
                    'market_value_in_eur': int,
                    'height_in_cm': float,
                    'sub_position_name': str,
                    'sub_position_freq': float,
                    'foot_name': str,
                    'foot_encoded': int, 
                    'position_name': str,
                    'pos_Attack': int, 
                    'pos_Defender': int, 
                    'pos_Goalkeeper': int, 
                    'pos_Midfield': int, 
                    'age_at_valuation': float 
                    })

# Ensuring date types
valuation_profiles['date'] = pd.to_datetime(valuation_profiles['date'])
valuation_profiles['date_of_birth'] = pd.to_datetime(valuation_profiles['date_of_birth'])

# Ensuring data is sorted
valuation_profiles = valuation_profiles.sort_values(['player_id', 'date']).reset_index(drop=True)

print("valuation_profiles shape:", valuation_profiles.shape)
print(f"Date range: {valuation_profiles['date'].min()} to {valuation_profiles['date'].max()}")
valuation_profiles.head()

# Keep here at bottom to check on df when needed
# print("-"*60)
# print("Missing values in valuation_profiles:")
# print("-"*60)
# display(valuation_profiles.isna().sum().sort_values(ascending=False).head(len(valuation_profiles)))

valuation_profiles shape: (480533, 15)
Date range: 2001-07-20 00:00:00 to 2025-04-06 00:00:00

,player_id,date,market_value_in_eur,height_in_cm,sub_position_name,sub_position_freq,foot_name,foot_encoded,date_of_birth,position_name,pos_Attack,pos_Defender,pos_Goalkeeper,pos_Midfield,age_at_valuation
0,10,2004-10-04,7000000,184.0,Centre-Forward,0.140497,right,1,1978-06-09,Attack,1,0,0,0,26.32
1,10,2005-01-07,9000000,184.0,Centre-Forward,0.140497,right,1,1978-06-09,Attack,1,0,0,0,26.58
2,10,2005-05-05,12000000,184.0,Centre-Forward,0.140497,right,1,1978-06-09,Attack,1,0,0,0,26.90
3,10,2005-09-30,15000000,184.0,Centre-Forward,0.140497,right,1,1978-06-09,Attack,1,0,0,0,27.31
4,10,2006-01-09,20000000,184.0,Centre-Forward,0.140497,right,1,1978-06-09,Attack,1,0,0,0,27.59

In [426]:
# Merging app_for_merge with lu_for_merge

# Merging app_for_merge (Appearance Info) with lu_for_merge (Lineup Info)
game_stats = app_for_merge.merge(lu_for_merge, on=['player_id', 'date'], how='inner')

# Time discrepancy from inital date between both datasets
game_stats.drop(columns=['total_starts', 'total_captaincies', 'starting_rate', 'captain_rate'], 
                inplace=True)

# Ensuring general types
game_stats = game_stats.astype({'player_id': int,
                    'total_goals': int,
                    'total_assists': int,
                    'total_minutes': int,
                    'total_yellow_cards': int,
                    'total_red_cards': int,
                    'total_appearances': int, 
                    'goal_rate': float,
                    'assist_rate': float, 
                    'yellow_card_rate': float, 
                    'red_card_rate': float, 
                    'is_starter': int, 
                    'team_captain': int 
                    })

# Ensuring date types
game_stats['date'] = pd.to_datetime(game_stats['date'])

# Ensuring data is sorted
game_stats = game_stats.sort_values(['player_id', 'date']).reset_index(drop=True)

print(f"game_stats shape: {game_stats.shape}")
print(f"Date range: {game_stats['date'].min()} to {game_stats['date'].max()}")
game_stats.head()

# Keep here at bottom to check on df when needed
# print("-"*60)
# print("Missing values in game_stats:")
# print("-"*60)
# display(game_stats.isna().sum().sort_values(ascending=False).head(len(game_stats)))

game_stats shape: (1342295, 14)
Date range: 2013-07-02 00:00:00 to 2024-03-17 00:00:00

,player_id,date,total_goals,total_assists,total_minutes,total_yellow_cards,total_red_cards,total_appearances,goal_rate,assist_rate,yellow_card_rate,red_card_rate,is_starter,team_captain
0,10,2013-08-18,16,3,2675,8,0,37,0.432,0.081,0.216,0.0,1,0
1,10,2013-08-25,16,5,2758,8,0,38,0.421,0.132,0.211,0.0,1,0
2,10,2013-08-31,17,5,2840,8,0,39,0.436,0.128,0.205,0.0,1,0
3,10,2013-09-15,17,5,2930,8,0,40,0.425,0.125,0.200,0.0,1,0
4,10,2013-09-22,17,5,3020,8,0,41,0.415,0.122,0.195,0.0,1,0

### CHECKPOINT 2

We now have two datasets formed by merges:
- `valuation_profiles`: player_id, date, market_value_in_eur, height_in_cm, sub_position_name, sub_position_freq, foot_name, foot_encoded, date_of_birth, position_name, pos_Attack, pos_Defender, pos_Goalkeeper, pos_Midfield, age_at_valuation
- `game_stats`: player_id, date, total_goals, total_assists, total_minutes, total_yellow_cards, total_red_cards, total_appearances, goal_rate, assist_rate, yellow_card_rate, red_card_rate, is_starter, team_captain

In [427]:
""" DIRECT MERGE_ASOF PRODUCES PERSISTENT ERROR """
# ---------------------------------------------------------------------------
# ValueError                                Traceback (most recent call last)
# Cell In[132], line 8
#       5 game_stats = game_stats.sort_values(['player_id', 'date']).reset_index(drop=True)
#       7 # Merge: get most recent game stats before each valuation
# ----> 8 total_merge = pd.merge_asof(
#       9     valuation_profiles.sort_values(['player_id', 'date']).reset_index(drop=True),
#      10     game_stats.sort_values(['player_id', 'date']).reset_index(drop=True),
#      11     on='date',
#      12     by='player_id',
#      13     direction='backward'
#      14 )
#      16 # Filter to dates where game data exists
#      17 total_merge = total_merge[total_merge['date'] >= '2012-07-01'].copy()

# File /opt/anaconda3/envs/final_project_data_env/lib/python3.12/site-packages/pandas/core/reshape/merge.py:708, in merge_asof(left, right, on, left_on, right_on, left_index, right_index, by, left_by, right_by, suffixes, tolerance, allow_exact_matches, direction)
#     456 ***
#     457 Perform a merge by key distance.
#     458 
#    (...)    689 4 2016-05-25 13:30:00.048   AAPL   98.00       100     NaN     NaN
#     690 ***
#     691 op = _AsOfMerge(
#     692     left,
#     693     right,
#    (...)    706     direction=direction,
# ...
# -> 2183     raise ValueError(f"{side} keys must be sorted")
#    2185 if isinstance(values, ArrowExtensionArray):
#    2186     values = values._maybe_convert_datelike_array()

# ValueError: left keys must be sorted

# REASON:
# pd.merge_asof requires that ALL dates be in order chronologically, but the dates in the dataset restart/jump back everytime there is a new player_id

# Error-producing code:

# # Sort both datasets
# valuation_profiles = valuation_profiles.sort_values(['player_id', 'date']).reset_index(drop=True)
# game_stats = game_stats.sort_values(['player_id', 'date']).reset_index(drop=True)

# # Merge: get most recent game stats before each valuation
# total_merge = pd.merge_asof(
#     valuation_profiles.sort_values(['player_id', 'date']).reset_index(drop=True),
#     game_stats.sort_values(['player_id', 'date']).reset_index(drop=True),
#     on='date',
#     by='player_id',
#     direction='backward'
# )

' DIRECT MERGE_ASOF PRODUCES PERSISTENT ERROR '

In [428]:
# Merging by splitting by player_id, merging on date, concatinating resulting tables (Slower solution to error)
all_merges = []
for player_id in valuation_profiles['player_id'].unique():
    vp = valuation_profiles[valuation_profiles['player_id'] == player_id].reset_index(drop=True)
    gs = game_stats[game_stats['player_id'] == player_id].drop(columns='player_id').reset_index(drop=True)
    
    if len(gs) > 0:
        merged = pd.merge_asof(vp, gs, on='date', direction='backward')
        all_merges.append(merged)

total_merge = pd.concat(all_merges, ignore_index=True)

In [429]:
print(type(total_merge))

<class 'pandas.core.frame.DataFrame'>

In [430]:
# Choosing random series to remove all nulls
total_merge = total_merge.dropna(subset=["assist_rate"])

# Ensuring data is sorted
total_merge = total_merge.sort_values(['player_id', 'date']).reset_index(drop=True)

# Ensure types 
total_merge = total_merge.astype({'player_id': int,
                                  'market_value_in_eur': int,
                                  'height_in_cm': float,
                                  'sub_position_name': str,
                                  'sub_position_freq': float,
                                  'foot_name': str,
                                  'foot_encoded': int,
                                  'position_name': str,
                                  'pos_Attack': int,
                                  'pos_Defender': int,
                                  'pos_Goalkeeper': int,
                                  'pos_Midfield': int,
                                  'age_at_valuation': float,
                                  'total_goals': int,
                                  'total_assists': int,
                                  'total_minutes': int,
                                  'total_yellow_cards': int,
                                  'total_red_cards': int,
                                  'total_appearances': int,
                                  'goal_rate': float,
                                  'assist_rate': float,
                                  'yellow_card_rate': float,
                                  'red_card_rate': float,
                                  'is_starter': int,
                                  'team_captain': int
})
total_merge['date'] = pd.to_datetime(total_merge['date'])
total_merge['date_of_birth'] = pd.to_datetime(total_merge['date_of_birth'])

print(total_merge.shape)
total_merge.head()

# Keep here at bottom to check on df when needed
# print("-"*60)
# print("Missing values in total_merge:")
# print("-"*60)
# display(total_merge.isna().sum().sort_values(ascending=False).head(len(total_merge)))

(264965, 27)

,player_id,date,market_value_in_eur,height_in_cm,sub_position_name,sub_position_freq,foot_name,foot_encoded,date_of_birth,position_name,pos_Attack,pos_Defender,pos_Goalkeeper,pos_Midfield,age_at_valuation,total_goals,total_assists,total_minutes,total_yellow_cards,total_red_cards,total_appearances,goal_rate,assist_rate,yellow_card_rate,red_card_rate,is_starter,team_captain
0,10,2014-01-07,1000000,184.0,Centre-Forward,0.140497,right,1,1978-06-09,Attack,1,0,0,0,35.58,21,5,3625,9,0,50,0.420,0.100,0.180,0.0,1,0
1,10,2014-07-07,1000000,184.0,Centre-Forward,0.140497,right,1,1978-06-09,Attack,1,0,0,0,36.08,24,8,4805,10,0,65,0.369,0.123,0.154,0.0,1,0
2,10,2015-01-07,1000000,184.0,Centre-Forward,0.140497,right,1,1978-06-09,Attack,1,0,0,0,36.58,28,11,5301,12,0,80,0.350,0.138,0.150,0.0,1,0
3,10,2015-07-01,1000000,184.0,Centre-Forward,0.140497,right,1,1978-06-09,Attack,1,0,0,0,37.06,40,17,7094,16,0,105,0.381,0.162,0.152,0.0,0,0
4,10,2016-01-04,1000000,184.0,Centre-Forward,0.140497,right,1,1978-06-09,Attack,1,0,0,0,37.57,40,19,7730,18,0,116,0.345,0.164,0.155,0.0,1,0

In [431]:
# Create target variable
total_merge['target_value'] = total_merge.groupby('player_id')['market_value_in_eur'].shift(-1)
total_merge['next_valuation_date'] = total_merge.groupby('player_id')['date'].shift(-1)
total_merge['days_until_next'] = (total_merge['next_valuation_date'] - total_merge['date']).dt.days

# Add historical value features
total_merge['value_lag_1'] = total_merge.groupby('player_id')['market_value_in_eur'].shift(1)
total_merge['value_change'] = total_merge['market_value_in_eur'] - total_merge['value_lag_1']
total_merge['value_change_pct'] = (total_merge['market_value_in_eur'] - total_merge['value_lag_1']) / total_merge['value_lag_1'].clip(lower=1)
total_merge['value_lag_1'] = total_merge['value_lag_1'].fillna(total_merge['market_value_in_eur'])
total_merge['value_change'] = total_merge['value_change'].fillna(0)
total_merge['value_change_pct'] = total_merge['value_change_pct'].fillna(0)

# Final cleanup
total_merge = total_merge.dropna(subset=['target_value']).copy()

# Ensuring sorted table
total_merge = total_merge.sort_values(['player_id', 'date']).reset_index(drop=True)

print(f"Final dataset: {total_merge.shape}")
total_merge.head(25)

# Keep here at bottom to check on df when needed
# print("-"*60)
# print("Missing values in total_merge:")
# print("-"*60)
# display(total_merge.isna().sum().sort_values(ascending=False).head(len(total_merge)))

Final dataset: (243583, 33)

,player_id,date,market_value_in_eur,height_in_cm,sub_position_name,sub_position_freq,foot_name,foot_encoded,date_of_birth,position_name,pos_Attack,pos_Defender,pos_Goalkeeper,pos_Midfield,age_at_valuation,total_goals,total_assists,total_minutes,total_yellow_cards,total_red_cards,total_appearances,goal_rate,assist_rate,yellow_card_rate,red_card_rate,is_starter,team_captain,target_value,next_valuation_date,days_until_next,value_lag_1,value_change,value_change_pct
0,10,2014-01-07,1000000,184.0,Centre-Forward,0.140497,right,1,1978-06-09,Attack,1,0,0,0,35.58,21,5,3625,9,0,50,0.420,0.100,0.180,0.000,1,0,1000000.0,2014-07-07,181.0,1000000.0,0.0,0.000000
1,10,2014-07-07,1000000,184.0,Centre-Forward,0.140497,right,1,1978-06-09,Attack,1,0,0,0,36.08,24,8,4805,10,0,65,0.369,0.123,0.154,0.000,1,0,1000000.0,2015-01-07,184.0,1000000.0,0.0,0.000000
2,10,2015-01-07,1000000,184.0,Centre-Forward,0.140497,right,1,1978-06-09,Attack,1,0,0,0,36.58,28,11,5301,12,0,80,0.350,0.138,0.150,0.000,1,0,1000000.0,2015-07-01,175.0,1000000.0,0.0,0.000000
3,10,2015-07-01,1000000,184.0,Centre-Forward,0.140497,right,1,1978-06-09,Attack,1,0,0,0,37.06,40,17,7094,16,0,105,0.381,0.162,0.152,0.000,0,0,1000000.0,2016-01-04,187.0,1000000.0,0.0,0.000000
4,26,2014-07-10,5000000,190.0,Goalkeeper,0.104977,left,0,1980-08-06,Goalkeeper,0,0,1,0,33.92,0,0,8256,3,2,92,0.000,0.000,0.033,0.022,1,1,3000000.0,2015-02-04,209.0,5000000.0,0.0,0.000000
5,26,2015-02-04,3000000,190.0,Goalkeeper,0.104977,left,0,1980-08-06,Goalkeeper,0,0,1,0,34.50,0,0,9966,3,2,111,0.000,0.000,0.027,0.018,1,0,2000000.0,2015-07-01,147.0,5000000.0,-2000000.0,-0.400000
6,26,2015-07-01,2000000,190.0,Goalkeeper,0.104977,left,0,1980-08-06,Goalkeeper,0,0,1,0,34.90,0,0,11136,3,2,124,0.000,0.000,0.024,0.016,1,0,1000000.0,2015-10-16,107.0,3000000.0,-1000000.0,-0.333333
7,26,2015-10-16,1000000,190.0,Goalkeeper,0.104977,left,0,1980-08-06,Goalkeeper,0,0,1,0,35.19,0,0,11586,3,2,129,0.000,0.000,0.023,0.016,1,0,1000000.0,2016-02-15,122.0,2000000.0,-1000000.0,-0.500000
8,26,2016-02-15,1000000,190.0,Goalkeeper,0.104977,left,0,1980-08-06,Goalkeeper,0,0,1,0,35.53,0,0,11946,3,2,133,0.000,0.000,0.023,0.015,1,0,1000000.0,2016-07-22,158.0,1000000.0,0.0,0.000000
9,26,2016-07-22,1000000,190.0,Goalkeeper,0.104977,left,0,1980-08-06,Goalkeeper,0,0,1,0,35.96,0,0,12396,4,2,138,0.000,0.000,0.029,0.014,1,0,1000000.0,2017-02-07,200.0,1000000.0,0.0,0.000000
10,26,2017-02-07,1000000,190.0,Goalkeeper,0.104977,left,0,1980-08-06,Goalkeeper,0,0,1,0,36.51,0,0,13416,4,2,149,0.000,0.000,0.027,0.013,1,0,1000000.0,2017-06-19,132.0,1000000.0,0.0,0.000000
11,26,2017-06-19,1000000,190.0,Goalkeeper,0.104977,left,0,1980-08-06,Goalkeeper,0,0,1,0,36.87,0,0,13416,4,2,149,0.000,0.000,0.027,0.013,1,0,750000.0,2017-12-28,192.0,1000000.0,0.0,0.000000
12,80,2014-07-10,1000000,194.0,Goalkeeper,0.104977,right,1,1981-03-18,Goalkeeper,0,0,1,0,33.31,0,0,630,0,0,7,0.000,0.000,0.000,0.000,1,0,500000.0,2015-02-04,209.0,1000000.0,0.0,0.000000
13,80,2015-02-04,500000,194.0,Goalkeeper,0.104977,right,1,1981-03-18,Goalkeeper,0,0,1,0,33.88,0,0,630,0,0,7,0.000,0.000,0.000,0.000,1,0,500000.0,2015-07-01,147.0,1000000.0,-500000.0,-0.500000
14,80,2015-07-01,500000,194.0,Goalkeeper,0.104977,right,1,1981-03-18,Goalkeeper,0,0,1,0,34.29,0,0,630,0,0,7,0.000,0.000,0.000,0.000,1,0,300000.0,2016-02-15,229.0,500000.0,0.0,0.000000
15,80,2016-02-15,300000,194.0,Goalkeeper,0.104977,right,1,1981-03-18,Goalkeeper,0,0,1,0,34.91,0,0,630,0,0,7,0.000,0.000,0.000,0.000,1,0,200000.0,2016-07-22,158.0,500000.0,-200000.0,-0.400000
16,80,2016-07-22,200000,194.0,Goalkeeper,0.104977,right,1,1981-03-18,Goalkeeper,0,0,1,0,35.35,0,0,630,0,0,7,0.000,0.000,0.000,0.000,1,0,200000.0,2017-02-07,200.0,300000.0,-100000.0,-0.333333
17,80,2017-02-07,200000,194.0,Goalkeeper,0.104977,right,1,1981-03-18,Goalkeeper,0,0,1,0,35.89,0,0,630,0,0,7,0.000,0.000,0.000,0.000,1,0,200000.0,2017-06-19,132.0,200000.0,0.0,0.000000
18,80,2017-06-19,200000,194.0,Goalkeeper,0.104977,right,1,1981-03-18,Goalkeeper,0,0,1,0,36.25,0,0,900,0,0,10,0.000,0.000,0.000,0.000,1,0,100000.0,2017-09-21,94.0,200000.0,0.0,0.000000
19,80,2017-09-21,100000,194.0,Goalkeeper,0.104977,right,1,1981-03-18,Goalkeeper,0,0,1,0,36.51,0,0,900,0,0,10,0.000,0.000,0.000,0.000,1,0,100000.0,2017-12-28,98.0,200000.0,-100000.0,-0.500000
20,80,2017-12-28,100000,194.0,Goalkeeper,0.104977,right,1,1981-03-18,Goalkeeper,0,0,1,0,36.78,0,0,1080,0,0,12,0.000,0.000,0.000,0.000,1,0,100000.0,2018-06-05,159.0,100000.0,0.0,0.000000
21,132,2014-01-15,2000000,179.0,Attacking Midfield,0.068803,both,2,1980-10-04,Midfield,0,0,0,1,33.28,4,2,2181,7,0,35,0.114,0.057,0.200,0.000,0,0,2000000.0,2014-08-12,209.0,2000000.0,0.0,0.000000
22,132,2014-08-12,2000000,179.0,Attacking Midfield,0.068803,both,2,1980-10-04,Midfield,0,0,0,1,33.85,6,2,3156,12,0,54,0.111,0.037,0.222,0.000,0,0,2000000.0,2015-02-12,184.0,2000000.0,0.0,0.000000
23,132,2015-02-12,2000000,179.0,Attacking Midfield,0.068803,both,2,1980-10-04,Midfield,0,0,0,1,34.36,8,4,3805,13,0,69,0.116,0.058,0.188,0.000,1,0,1500000.0,2015-07-01,139.0,2000000.0,0.0,0.000000
24,132,2015-07-01,1500000,179.0,Attacking Midfield,0.068803,both,2,1980-10-04,Midfield,0,0,0,1,34.74,9,4,3968,13,0,76,0.118,0.053,0.171,0.000,0,0,1500000.0,2016-02-09,223.0,2000000.0,-500000.0,-0.250000

### SECTION 1 COMPLETE

`total_merge` represents the final dataset after all cleaning and engineering. It contains the following information:

In [ ]:
# Feature Discretization
print("=" * 60)
print("=== Feature Discretization ===")
print("=" * 60)

# Age groups based on football career stages
merged_df['age_group'] = pd.cut(
    merged_df['age_at_valuation'], 
    bins=[0, 23, 28, 33, 50], 
    labels=['Young (≤23)', 'Prime (24-28)', 'Experienced (29-33)', 'Veteran (34+)']
)

# Valuation tiers
merged_df['value_tier'] = pd.cut(
    merged_df['market_value_in_eur_valuation'], 
    bins=[0, 1e6, 5e6, 20e6, float('inf')],
    labels=['Low (<1M)', 'Medium (1-5M)', 'High (5-20M)', 'Elite (>20M)']
)

# Target value tiers (for next year prediction)
merged_df['target_value_tier'] = pd.cut(
    merged_df['market_value_next_year'], 
    bins=[0, 1e6, 5e6, 20e6, float('inf')],
    labels=['Low (<1M)', 'Medium (1-5M)', 'High (5-20M)', 'Elite (>20M)']
)

print("\nSample of discretized features:")
print(merged_df[['player_id', 'age_at_valuation', 'age_group', 
                  'market_value_in_eur_valuation', 'value_tier']].head(10))

print(f"\nAge Group Distribution:")
print(merged_df['age_group'].value_counts().sort_index())

print(f"\nCurrent Value Tier Distribution:")
print(merged_df['value_tier'].value_counts().sort_index())

print(f"\nTarget Value Tier Distribution:")
print(merged_df['target_value_tier'].value_counts().sort_index())

We build the feature matrix `X` and target `y`. We explicitly remove columns that would leak information (current valuation) and identifiers.

In [ ]:
# Build X/y (no leakage)

y = merged_encoded["market_value_next_year"]

drop_cols = [
    "market_value_next_year",
    "market_value_in_eur_valuation",
    "player_id",
    "date",
    "date_of_birth",
    "year"
]
X = merged_encoded.drop(columns=[c for c in drop_cols if c in merged_encoded.columns])

# Ensure numeric + dummy (bool) columns are kept
X = X.select_dtypes(include=[np.number, "bool"]).copy()

# Convert bool dummies to 0/1 ints for sklearn
bool_cols = X.select_dtypes(include=["bool"]).columns
if len(bool_cols) > 0:
    X[bool_cols] = X[bool_cols].astype(int)

# Clean inf/NaN
X = X.replace([np.inf, -np.inf], np.nan)
X = X.fillna(X.median(numeric_only=True))

print("X shape:", X.shape)
print("y shape:", y.shape)
print("Any NaNs in X?", X.isna().any().any())

## 2. Data Analysis and Visualization
- Identify categorical, ordinal, and numerical variables within data
- Provide measures of centrality and distribution with visualizations
- Diagnose for correlations between variables and determine independent and dependent variables
- Perform exploratory analysis in combination with visualization techniques to discover patterns and features of interest
- Create visualizations that allow for the discovery of insights in the data

In [ ]:
# Summary Statistics
print("=" * 60)
print("=== Measures of Centrality and Distribution ===")
print("=" * 60)

print("\n MODEL VARIABLES:")
print("Dependent Variable (Target): market_value_next_year")
print("Independent Variables: age_at_valuation, height_in_cm, position features,")
print("                       market_value_lag_1, market_value_lag_2, market_value_trend,")
print("                       market_value_mean_3, performance statistics (goals, assists,")
print("                       minutes_played, goals_per_90), and other historical features\n")

# Key numerical variables for analysis
key_vars = ['market_value_in_eur_valuation', 'market_value_next_year', 
            'age_at_valuation', 'height_in_cm', 
            'market_value_lag_1', 'market_value_trend',
            'total_goals', 'total_assists', 'total_minutes',
            'goals_per_90', 'assists_per_90', 'num_appearances']  

print("=" * 60)
print("Summary Statistics for Key Variables")
print("=" * 60)
summary_stats = merged_df[key_vars].describe()
display(summary_stats)

print("\n" + "=" * 60)
print("Additional Measures of Centrality")
print("=" * 60)
for var in key_vars:
    print(f"\n{var}:")
    print(f"  Mean:     €{merged_df[var].mean():,.2f}" if 'value' in var or 'market' in var 
          else f"  Mean:     {merged_df[var].mean():.2f}")
    print(f"  Median:   €{merged_df[var].median():,.2f}" if 'value' in var or 'market' in var 
          else f"  Median:   {merged_df[var].median():.2f}")
    mode_val = merged_df[var].mode()
    print(f"  Mode:     {mode_val[0]:.2f}" if len(mode_val) > 0 else "  Mode:     N/A")
    print(f"  Std Dev:  €{merged_df[var].std():,.2f}" if 'value' in var or 'market' in var 
          else f"  Std Dev:  {merged_df[var].std():.2f}")
    print(f"  Skewness: {merged_df[var].skew():.2f}")
    print(f"  Kurtosis: {merged_df[var].kurtosis():.2f}") # Peakness of probability distribution

print("\n" + "=" * 60)

In [ ]:
merged_df[["starts", "lineup_matches", "start_ratio", "captain_matches"]].describe()

In [ ]:
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.flatten()

for idx, pos in enumerate(["Attack", "Midfield", "Defender", "Goalkeeper"]):
    pos_data = merged_df[merged_df["position"] == pos]

    axes[idx].scatter(
        pos_data["start_ratio"],
        pos_data["market_value_in_eur_valuation"],
        alpha=0.4, s=15
    )
    axes[idx].set_title(f"{pos}: Start Ratio vs Market Value")
    axes[idx].set_xlabel("Start Ratio")
    axes[idx].set_ylabel("Market Value (EUR)")
    axes[idx].set_yscale("log")
    axes[idx].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

In [ ]:
# Boxplot: Market Value by Position, colored by goal-scoring performance
import seaborn as sns

plt.figure(figsize=(12, 6))
sns.boxplot(data=merged_df, x='position', y='market_value_in_eur_valuation')
plt.xlabel('Position')
plt.ylabel('Market Value (EUR)')
plt.title('Market Value Distribution by Position')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

In [ ]:
#Faceted Analysis: Goals by Position (active players)
print("Creating position-specific analysis for Goals...")
print("Note: Filtering to players with >0 goals to show meaningful relationships")

# Get unique positions
positions = merged_df['position'].value_counts().index[:4]

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.flatten()

for idx, pos in enumerate(positions):
    # Filter players with goals > 0
    pos_data = merged_df[(merged_df['position'] == pos) & (merged_df['total_goals'] > 0)].copy()
    
    axes[idx].scatter(pos_data['total_goals'], 
                      pos_data['market_value_in_eur_valuation'],
                      alpha=0.4, s=15, color='steelblue')
    axes[idx].set_xlabel('Total Goals (Season)', fontsize=10)
    axes[idx].set_ylabel('Market Value (EUR)', fontsize=10)
    axes[idx].set_title(f'{pos} - Goals vs Market Value\n(n={len(pos_data)} with goals)', 
                        fontsize=11, fontweight='bold')
    axes[idx].grid(True, alpha=0.3)
    
    # Add trend line and calculate statistics
    if len(pos_data) > 10:
        try:
            # Calculate correlation
            correlation = pos_data[['total_goals', 'market_value_in_eur_valuation']].corr().iloc[0, 1]
            
            # Calculate slope (linear regression)
            z = np.polyfit(pos_data['total_goals'], pos_data['market_value_in_eur_valuation'], 1)
            slope = z[0]
            p = np.poly1d(z)
            
            # Plot trend line
            x_trend = np.linspace(pos_data['total_goals'].min(), pos_data['total_goals'].max(), 100)
            axes[idx].plot(x_trend, p(x_trend), "r--", alpha=0.6, linewidth=2)
            
            # Add text box with statistics
            textstr = f'Slope: €{slope:,.0f}/goal\nCorr: {correlation:.3f}'
            props = dict(boxstyle='round', facecolor='wheat', alpha=0.8)
            axes[idx].text(0.95, 0.95, textstr, transform=axes[idx].transAxes, 
                          fontsize=9, verticalalignment='top', horizontalalignment='right',
                          bbox=props)
        except Exception as e:
            print(f"Could not calculate stats for {pos}: {e}")

plt.tight_layout()
plt.show()

# Print summary
print("\nData coverage after leakage fix:")
for pos in positions:
    total = len(merged_df[merged_df['position'] == pos])
    with_goals = len(merged_df[(merged_df['position'] == pos) & (merged_df['total_goals'] > 0)])
    print(f"  {pos}: {with_goals}/{total} ({with_goals/total*100:.1f}%) have goals before valuation")

In [ ]:
# Faceted Analysis: Assists by Position with Correlation Stats 
print("Creating position-specific analysis for Assists...")

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.flatten()

for idx, pos in enumerate(positions):
    pos_data = merged_df[merged_df['position'] == pos]
    
    axes[idx].scatter(pos_data['total_assists'], 
                      pos_data['market_value_in_eur_valuation'],
                      alpha=0.4, s=15, color='seagreen')
    axes[idx].set_xlabel('Total Assists (Season)', fontsize=10)
    axes[idx].set_ylabel('Market Value (EUR)', fontsize=10)
    axes[idx].set_title(f'{pos} - Assists vs Market Value (n={len(pos_data)})', 
                        fontsize=11, fontweight='bold')
    axes[idx].grid(True, alpha=0.3)
    
    # Add trend line and calculate statistics
    if len(pos_data) > 10:
        # Calculate correlation
        correlation = pos_data[['total_assists', 'market_value_in_eur_valuation']].corr().iloc[0, 1]
        
        # Calculate slope (linear regression)
        z = np.polyfit(pos_data['total_assists'], pos_data['market_value_in_eur_valuation'], 1)
        slope = z[0]
        p = np.poly1d(z)
        
        # Plot trend line
        x_trend = np.linspace(pos_data['total_assists'].min(), pos_data['total_assists'].max(), 100)
        axes[idx].plot(x_trend, p(x_trend), "r--", alpha=0.6, linewidth=2)
        
        # Add text box with statistics in top right
        textstr = f'Slope: €{slope:,.0f}/assist\nCorr: {correlation:.3f}'
        props = dict(boxstyle='round', facecolor='lightgreen', alpha=0.8)
        axes[idx].text(0.95, 0.95, textstr, transform=axes[idx].transAxes, 
                      fontsize=9, verticalalignment='top', horizontalalignment='right',
                      bbox=props)

plt.tight_layout()
plt.show()

In [ ]:
# Goal contributions = goals + assists (season totals)
merged_df["total_goal_contributions"] = merged_df["total_goals"] + merged_df["total_assists"]

# Look at per-90 since minutes are very uneven (already made goal_contributions_per_90 in perf_stats, this just ensures it exists in merged_df)

positions = ["Attack", "Midfield", "Defender", "Goalkeeper"]

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.flatten()

for idx, pos in enumerate(positions):
    pos_data = merged_df[merged_df["position"] == pos].copy()

    # helpful: drop missing/inf just for plotting
    pos_data = pos_data.replace([np.inf, -np.inf], np.nan).dropna(
        subset=["total_goal_contributions", "market_value_in_eur_valuation"]
    )

    axes[idx].scatter(
        pos_data["total_goal_contributions"],
        pos_data["market_value_in_eur_valuation"],
        alpha=0.35, s=15
    )
    axes[idx].set_xlabel("Total Goal Contributions (Goals + Assists)")
    axes[idx].set_ylabel("Market Value (EUR)")
    axes[idx].set_title(f"{pos} — Goal Contributions vs Market Value (n={len(pos_data)})")
    axes[idx].grid(True, alpha=0.3)

    if len(pos_data) > 10:
        corr = pos_data[["total_goal_contributions", "market_value_in_eur_valuation"]].corr().iloc[0, 1]
        z = np.polyfit(pos_data["total_goal_contributions"], pos_data["market_value_in_eur_valuation"], 1)
        slope = z[0]
        p = np.poly1d(z)

        x_trend = np.linspace(pos_data["total_goal_contributions"].min(),
                              pos_data["total_goal_contributions"].max(), 100)
        axes[idx].plot(x_trend, p(x_trend), "r--", alpha=0.7, linewidth=2)

        axes[idx].text(
            0.95, 0.95,
            f"Slope: €{slope:,.0f}/(G+A)\nCorr: {corr:.3f}",
            transform=axes[idx].transAxes,
            ha="right", va="top", fontsize=9,
            bbox=dict(boxstyle="round", alpha=0.8)
        )

plt.tight_layout()
plt.show()

In [ ]:
# Statistics

display(y.describe())

plt.figure()
plt.hist(y, bins=60)
plt.xlabel("Market Value Next Year (EUR)")
plt.ylabel("Count")
plt.title("Distribution of Target: Next Year Market Value")
plt.show()

In [ ]:
# age vs next-year value

plt.figure()
plt.scatter(merged_df["age_at_valuation"], merged_df["market_value_next_year"], s=2)
plt.xlabel("Age at Valuation")
plt.ylabel("Next Year Market Value (EUR)")
plt.title("Age vs Next Year Market Value")
plt.show()

In [ ]:
# Minutes Played Distribution
plt.figure(figsize=(10, 5))
plt.hist(merged_df['total_minutes'], bins=50, edgecolor='black')
plt.xlabel('Total Minutes Played (Season)')
plt.ylabel('Frequency')
plt.title('Distribution of Playing Time')
plt.tight_layout()
plt.show()

In [ ]:
# Market Value by Performance Tier (boxplot)
# Create performance tiers
merged_df['performance_tier'] = pd.cut(
    merged_df['total_goals'], 
    bins=[0, 1, 5, 10, 100], 
    labels=['Low (0-1)', 'Medium (2-5)', 'High (6-10)', 'Elite (11+)']
)

plt.figure(figsize=(10, 6))
merged_df.boxplot(column='market_value_in_eur_valuation', by='performance_tier', 
                  figsize=(10, 6))
plt.xlabel('Goal-Scoring Performance Tier')
plt.ylabel('Market Value (EUR)')
plt.title('Market Value Distribution by Goal-Scoring Performance')
plt.suptitle('')  # Remove default title
plt.tight_layout()
plt.show()

In [ ]:
# Correlation heatmap 
import seaborn as sns

# Select key features including performance stats
corr_features = ['market_value_in_eur_valuation', 'market_value_next_year',
                 'age_at_valuation', 'height_in_cm',
                 'market_value_lag_1', 'market_value_lag_2',
                 'total_goals', 'total_assists', 'total_minutes',
                 'goals_per_90', 'assists_per_90', 'num_appearances']

corr_matrix = merged_df[corr_features].corr()

plt.figure(figsize=(12, 10))
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', 
            square=True, linewidths=0.5)
plt.title('Correlation Matrix: Market Value and Performance Features')
plt.tight_layout()
plt.show()

## 4. Data Analytics (Modeling)
This is a **supervised learning regression** problem. We compare multiple algorithms and evaluate them using MAE, RMSE, and R². We also do time-aware train/test splitting to reduce leakage risk.

In [ ]:
# Train/Test split (time-aware)
# We preserve order (shuffle=False) because data is time-dependent.

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

print("Train:", X_train.shape, y_train.shape)
print("Test:", X_test.shape, y_test.shape)

We compare:
- Linear Regression (baseline)
- ElasticNet (regularized linear)
- Random Forest (non-linear)
- KNN (distance-based)

For KNN and ElasticNet we benefit from scaling, so we use pipelines.

In [ ]:
# Models + evaluation

# def evaluate_model(name, model, X_tr, y_tr, X_te, y_te):
#     """
#     Train model, evaluate on test set, and perform cross-validation
#     """
#     # Train the model
#     model.fit(X_tr, y_tr)
    
#     # Test set predictions
#     pred = model.predict(X_te)
    
#     # Cross-validation on training set (5-fold)
#     print(f"\n{'='*60}")
#     print(f"Cross-Validation: {name}")
#     print(f"{'='*60}")
    
#     cv_r2 = cross_val_score(model, X_tr, y_tr, cv=5, scoring='r2', n_jobs=-1)
#     cv_mae = -cross_val_score(model, X_tr, y_tr, cv=5, scoring='neg_mean_absolute_error', n_jobs=-1)
#     cv_rmse = np.sqrt(-cross_val_score(model, X_tr, y_tr, cv=5, scoring='neg_mean_squared_error', n_jobs=-1))
    
#     print(f"  R² scores:   {cv_r2}")
#     print(f"  Mean R²:     {cv_r2.mean():.4f} (+/- {cv_r2.std():.4f})")
#     print(f"  MAE scores:  {cv_mae}")
#     print(f"  Mean MAE:    €{cv_mae.mean():,.2f} (+/- €{cv_mae.std():,.2f})")
#     print(f"  RMSE scores: {cv_rmse}")
#     print(f"  Mean RMSE:   €{cv_rmse.mean():,.2f} (+/- €{cv_rmse.std():,.2f})")
    
#     return {
#         "Model": name,
#         "MAE": mean_absolute_error(y_te, pred),
#         "RMSE": np.sqrt(mean_squared_error(y_te, pred)),
#         "R2": r2_score(y_te, pred),
#         "CV_R2_Mean": cv_r2.mean(),
#         "CV_R2_Std": cv_r2.std(),
#         "CV_MAE_Mean": cv_mae.mean(),
#         "CV_RMSE_Mean": cv_rmse.mean()
#     }

models = []

# Baselines (no scaling needed)
models.append(("Linear Regression", LinearRegression()))
models.append(("Random Forest", RandomForestRegressor(
    n_estimators=150,
    max_depth=18,
    random_state=42,
    n_jobs=-1
)))

# Pipelines (imputer + scaler) helps for KNN/ElasticNet
elastic_pipe = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("model", ElasticNet(alpha=0.1, l1_ratio=0.5, random_state=42))
])

knn_pipe = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("model", KNeighborsRegressor(n_neighbors=10))
])

models.append(("ElasticNet (scaled)", elastic_pipe))
models.append(("KNN (scaled)", knn_pipe))

results = []
for name, model in models:
    results.append(evaluate_model(name, model, X_train, y_train, X_test, y_test))

results_df = pd.DataFrame(results).sort_values("MAE")
results_df

We use `TimeSeriesSplit` to evaluate models with time-aware cross-validation. This avoids mixing future information into training folds.

In [ ]:
# TimeSeries cross-validation (on a subset for speed)

tscv = TimeSeriesSplit(n_splits=5)

# For speed, sample a subset
sample_size = min(120000, len(X_train))
X_cv = X_train.iloc[:sample_size]
y_cv = y_train.iloc[:sample_size]

# # Use MAE (negative in sklearn scoring conventions)
# def cv_mae(model):
#     scores = cross_val_score(
#         model, X_cv, y_cv,
#         cv=tscv,
#         scoring="neg_mean_absolute_error",
#         n_jobs=-1
#     )
#     return -scores.mean(), scores.std()

cv_rows = []
for name, model in models:
    mean_mae, std_mae = cv_mae(model)
    cv_rows.append({"Model": name, "CV_MAE_mean": mean_mae, "CV_MAE_std": std_mae})

cv_df = pd.DataFrame(cv_rows).sort_values("CV_MAE_mean")
cv_df

We inspect which features contribute most to predictions (interpretability).

In [ ]:
# Feature importance (Random Forest)

# Train Random Forest
rf = RandomForestRegressor(
    n_estimators=150,
    max_depth=18,
    random_state=42,
    n_jobs=-1
)
rf.fit(X_train, y_train)

# Compute importances
importances = pd.Series(
    rf.feature_importances_,
    index=X_train.columns
).sort_values(ascending=False)

top_k = 15
display(importances.head(top_k))

# Plot feature importances
top_feats = importances.head(top_k)

x = np.arange(len(top_feats))
y = top_feats.to_numpy(dtype=float)

plt.figure(figsize=(10, 5))
plt.bar(x, y)
plt.xticks(x, top_feats.index, rotation=90)
plt.ylabel("Importance")
plt.title(f"Top {top_k} Feature Importances (Random Forest)")
plt.tight_layout()
plt.show()

In [ ]:
# Analyze top performing features 
print("=" * 60)
print("Top 20 Feature Importances (Random Forest)")
print("=" * 60)

# Get feature importances from your trained RF model
rf = RandomForestRegressor(n_estimators=150, max_depth=18, random_state=42, n_jobs=-1)
rf.fit(X_train, y_train)

importances = pd.Series(rf.feature_importances_, index=X_train.columns).sort_values(ascending=False)

print("\nTop 20 Features:")
display(importances.head(20))

# Highlight performance features
print("\n Performance-Related Features in Top 20:")
perf_feature_keywords = ['goal', 'assist', 'minutes', 'appearance', 'cards']
top_20_features = importances.head(20)
for feat in top_20_features.index:
    if any(keyword in feat.lower() for keyword in perf_feature_keywords):
        print(f"  - {feat}: {top_20_features[feat]:.4f}")

A quick diagnostic plot to visually assess model fit.

In [ ]:
# Predicted vs actual

best_model_name = results_df.iloc[0]["Model"]
best_model = dict(models)[best_model_name]
best_model.fit(X_train, y_train)
pred = best_model.predict(X_test)

min_val = min(y_test.min(), pred.min())
max_val = max(y_test.max(), pred.max())

plt.figure()
plt.scatter(y_test, pred, s=2)

plt.xlim(min_val, max_val)
plt.ylim(min_val, max_val)

plt.gca().set_aspect("equal", adjustable="box")

plt.plot([min_val,max_val],[min_val,max_val],linestyle='--')

plt.xlabel("Actual Next Year Value (EUR)")
plt.ylabel("Predicted Next Year Value (EUR)")
plt.title(f"Predicted vs Actual - {best_model_name}")
plt.show()

In [ ]:

# Predicted vs Actual 

final_model_name = results_df.iloc[0]["Model"]
final_model = dict(models)[final_model_name]

final_model.fit(X_train, y_train)
pred = final_model.predict(X_test)

# Convert to numpy arrays and remove non-positive values for log scaling
y_true = np.asarray(y_test).astype(float)
y_pred = np.asarray(pred).astype(float)

mask = (y_true > 0) & (y_pred > 0) & np.isfinite(y_true) & np.isfinite(y_pred)
y_true = y_true[mask]
y_pred = y_pred[mask]

# 1) HEXBIN DENSITY PLOT (final when there are many points)
plt.figure(figsize=(8, 6))
hb = plt.hexbin(y_true, y_pred, gridsize=60, bins='log')  # density in log bins
plt.colorbar(hb, label="Log(count)")

# Log scales (makes long-tail readable)
plt.xscale("log")
plt.yscale("log")

# 45-degree line (perfect predictions)
min_v = min(y_true.min(), y_pred.min())
max_v = max(y_true.max(), y_pred.max())
plt.plot([min_v, max_v], [min_v, max_v], linewidth=2)

# Fit line to log10 values to show overall calibration
logx = np.log10(y_true)
logy = np.log10(y_pred)
m, b = np.polyfit(logx, logy, 1)
x_line = np.logspace(np.log10(min_v), np.log10(max_v), 200)
y_line = 10**(m*np.log10(x_line) + b)
plt.plot(x_line, y_line, linestyle="--", linewidth=2)

plt.xlabel("Actual Next Year Value (EUR) [log scale]")
plt.ylabel("Predicted Next Year Value (EUR) [log scale]")
plt.title(f"Predicted vs Actual (Density) – {final_model_name}")
plt.tight_layout()
plt.show()

In [ ]:


import numpy as np
import matplotlib.pyplot as plt


# Data (means + std)
models = ["Linear Regression", "Random Forest", "Elastic Net", "KNN"]

rmse_mean = np.array([3514054.36, 3107443.18, 3539581.11, 3906834.12])
rmse_std  = np.array([ 436867.97,  398525.41,  433502.17,  354739.85])

mae_mean  = np.array([1455708.91, 1150255.09, 1480353.46, 1524688.70])
mae_std   = np.array([ 121645.48,  115763.99,  129446.17,  155889.87])

r2_mean   = np.array([0.6806, 0.7506, 0.6760, 0.6040])
r2_std    = np.array([0.0310, 0.0239, 0.0296, 0.0172])

rmse_m = rmse_mean / 1e6
rmse_s = rmse_std  / 1e6
mae_m  = mae_mean  / 1e6
mae_s  = mae_std   / 1e6

# Plot (grouped bars)
x = np.arange(len(models))
width = 0.24

fig, ax1 = plt.subplots(figsize=(12, 6))

# Colors by metric 
c_rmse = "#e76f51"
c_mae  = "#2a9d8f"
c_r2   = "#264653"

# Left axis: MAE + RMSE (EUR, millions)
b_mae = ax1.bar(x - width, mae_m, width, yerr=mae_s, capsize=4, label="MAE (€M)", color=c_mae)
b_rmse = ax1.bar(x,        rmse_m, width, yerr=rmse_s, capsize=4, label="RMSE (€M)", color=c_rmse)

ax1.set_ylabel("Error (EUR, Millions)")
ax1.set_xticks(x)
ax1.set_xticklabels(models, rotation=15, ha="right")
ax1.grid(axis="y", alpha=0.25)

# Right axis: R²
ax2 = ax1.twinx()
b_r2 = ax2.bar(x + width, r2_mean, width, yerr=r2_std, capsize=4, label="R²", color=c_r2)
ax2.set_ylabel("R²")
ax2.set_ylim(0, 1.0)

# Title + combined legend
plt.title("Model Performance Comparison (Mean ± Std)")
handles1, labels1 = ax1.get_legend_handles_labels()
handles2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(handles1 + handles2, labels1 + labels2, loc="upper right")

plt.tight_layout()
plt.show()

## 5. Summary / Conclusions

- We framed the task as **supervised regression** to predict next-year market value.  
- We used **time-aware feature engineering** (lags, trends, rolling means) and a **time-aware train/test split** to reduce leakage risk.  
- We compared multiple models and evaluated them with **MAE, RMSE, and R²**, then validated via **TimeSeriesSplit** cross-validation.